### PR TITLE
NetCDF Output

### PR DESCRIPTION
**Pull request by akubaryk**
Adds the option for by-model-level WAM output into wam_fields.nc. There is standard compression applied, and the user can select both the cadence and the variables which are output into the NetCDF file.

### CODE REVIEW

**Comment by ZhuxiaoLi66** [comment]
@akubaryk the branch has been tested this morning, would like to confirm with you that the right place for the NetCDF output is PTMP directory. the one in WAM_output is the last run for restart runs. 
Also check the Neutral Temp. output, seems good. 
Would like to check one more variable (number density) later, should got improved this afternoon.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk checked another variable, verified the output variable writing.

**Comment by ZhuxiaoLi66** [comment]
netcdf_output_branch
v2_branch_diff_init

**Review by ZhuxiaoLi66 — COMMENTED** [review]
checked the netcdf output files and variables, confirmed that there is no problem on output variables and the job submit script is very handy.

**Review by ZhuxiaoLi66 — APPROVED** [review]
The netcdf output files (in PTMP) and variables are double checked, the writing out looks as expected.

**Comment by ZhuxiaoLi66** [comment]
@akubaryk just would like to confirm with you, we should checked the netCDF output in ./PTMP dir instead of ./WAM_output dir for restart runs, since all the output and input of former runs seems has over written by the following runs, and only the output of last run can be kept in ./WAM_output.

**Review by twfang — APPROVED** [review]

**Pull request merged**
